name: gnn-hulk
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=12.1
  - pip
  - pip:
    - torch-geometric
    - networkx
    - pandas
    - scikit-learn
    - matplotlib
    - umap-learn
